apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-prod

resources:
  - ../../../../../shared/argo/analysis-templates/prometheus-success-rate.yaml

helmCharts:
  - name: demo-app
    repo: oci://819211779624.dkr.ecr.us-west-2.amazonaws.com/demo-app-chart
    version: "0.0.0"   # update to semver on promotion
    releaseName: demo-app
    valuesFiles:
      - ../shared-prod-values.yaml
      - ./values-override.yaml
