apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-prod

resources:
  - ../../../../../shared/argo/analysis-templates/prometheus-success-rate.yaml

helmGlobals:
  chartHome: ../../../../../../go-app/deploy

helmCharts:
  - name: demo-app
    releaseName: demo-app
    valuesFile: ../shared-prod-values.yaml
    additionalValuesFiles:
      - ./values-override.yaml
