apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-dev   # Kustomize injects this into every rendered resource

helmGlobals:
  chartHome: ../../../../../../go-app/deploy

helmCharts:
  - name: demo-app
    releaseName: demo-app
    valuesFile: ../shared-dev-values.yaml      # env-wide: image.tag, strategy, replicas
    additionalValuesFiles:
      - ./values-override.yaml                   # cluster-specific: region, ingress host
