# gitops-manifests/projects/demo-app/environments/dev/shared-dev-values.yaml
# CI writes image.tag here on every push to main.
image:
  repository: 819211779624.dkr.ecr.us-west-2.amazonaws.com/demo-app
  tag: "sha-d1405f4"

rollout:
  strategy: instant

replicaCount: 1

metrics:
  enabled: true

loadgen:
  enabled: false
