# gitops-manifests/projects/demo-app/environments/staging/shared-staging-values.yaml
# Manually updated (rollouts-demo) on promotion from dev.
#
# Local dev:  repository: demo-app  /  tag: local
# AWS/ECR:    repository: 819211779624.dkr.ecr.us-west-2.amazonaws.com/demo-app  /  tag: <semver>
image:
  repository: demo-app
  tag: "local"
  # repository: 819211779624.dkr.ecr.us-west-2.amazonaws.com/demo-app
  # tag: "sha-c1abbd3"

rollout:
  strategy: blueGreen

replicaCount: 2

metrics:
  enabled: true

loadgen:
  enabled: false

holmesgpt:
  enabled: false
