apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rollouts-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo Rollouts demo project — manual promotion
  sourceRepos:
    - https://github.com/koolhandluke/argo-rollouts-demo.git
    - oci://819211779624.dkr.ecr.us-west-2.amazonaws.com/demo-app-chart
  destinations:
    - server: https://kubernetes.default.svc
      namespace: rollouts-dev-cluster-default
    - server: https://kubernetes.default.svc
      namespace: rollouts-staging-cluster-us-east
    - server: https://kubernetes.default.svc
      namespace: rollouts-prod-cluster-us-west
    - server: https://kubernetes.default.svc
      namespace: rollouts-prod-cluster-us-east
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: ClusterAnalysisTemplate
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
